### ISSUE TITLE
Uncaught Error: CSVDataError: Illegal Data

### ISSUE THREAD

**Issue by codywohlers** [evanplaice/jquery-csv#79]
I can't seem to import this [simple csv file](https://www.dropbox.com/s/ha24elor10xoscm/test.csv?dl=0) using `$.csv.toArray()`  I'm pretty sure it's stalling at the newline.

error:
```
jquery.csv.min.js:1 Uncaught Error: CSVDataError: Illegal Data [Row:1][Col:2]
    at http://localhost/sched-site/lib/jquery.csv.min.js:1:4031
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (native)
    at Object.parseEntry (http://localhost/sched-site/lib/jquery.csv.min.js:1:3513)
    at Object.toArray (http://localhost/sched-site/lib/jquery.csv.min.js:1:4785)
    at Object.success (http://localhost/sched-site/:29:44)
    at fire (http://localhost/sched-site/lib/jquery-1.8.2.js:974:30)
    at Object.fireWith [as resolveWith] (http://localhost/sched-site/lib/jquery-1.8.2.js:1082:7)
    at done (http://localhost/sched-site/lib/jquery-1.8.2.js:7788:14)
    at XMLHttpRequest.callback (http://localhost/sched-site/lib/jquery-1.8.2.js:8500:8)
```

code:
```
<script src="lib/jquery-1.8.2.js"</script>
<script src="lib/jquery-ui-1.9.0.js"></script>
<script src="lib/jquery.csv.min.js"></script>
...
inputTasks = $.csv.toArray(inputTasksCSV);
```

[csv file](https://www.dropbox.com/s/ha24elor10xoscm/test.csv?dl=0):
```
$ cat -A test.csv
test1,test2$
1,2$
```

system:
`Chromium 57.0.2987.98 Built on Ubuntu , running on neon 16.04`

**Comment by codywohlers** [comment]
Never mind!  Accidentally used `toArray()` instead of `toArrays()`

**Comment by evanplaice** [comment]
Glad I could be of assistance 😎 👍
